<?php

namespace ContainerTRKwp0u;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QnXkiGCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qnXkiGC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qnXkiGC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'output' => ['privates', '.errored..service_locator.qnXkiGC.Symfony\\Component\\Console\\Output\\ConsoleOutputInterface', NULL, 'Cannot autowire service ".service_locator.qnXkiGC": it references interface "Symfony\\Component\\Console\\Output\\ConsoleOutputInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'output' => 'Symfony\\Component\\Console\\Output\\ConsoleOutputInterface',
        ]);
    }
}
