<?php

namespace ContainerTRKwp0u;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsoleOutputInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qnXkiGC.Symfony\Component\Console\Output\ConsoleOutputInterface' shared service.
     *
     * @return \Symfony\Component\Console\Output\ConsoleOutputInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qnXkiGC": it references interface "Symfony\\Component\\Console\\Output\\ConsoleOutputInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
