version: '3'

services:
  mysqldb:
    container_name: db
    image: mariadb:10.7
    env_file:
      - environment/dev/mysql.env
    environment:
      - MYSQL_ROOT_PASSWORD=lSj58osiU12kjdj43shaSDDz
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.1
    env_file:
      - environment/dev/phpmyadmin.env
    volumes:
      - /sessions
    ports:
      - 127.0.0.1:8889:80
    restart: always
  
  symfony:
    container_name: symfony
    image: fguntz/symfony:2.0
    env_file:
      - environment/dev/symfony.env
    volumes:
      - ./symfony/php-dev.ini:/usr/local/etc/php/php.ini:ro
      - ./symfony/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ../:/var/www/app
      - app-vendor:/var/www/app/vendor
    working_dir: /var/www/app
    restart: always
    command: bash -c "composer install && php-fpm"

  www_wilo:
    container_name: www_wilo
    image: nginx:1.21.6-alpine
    depends_on:
      - symfony
    volumes:
      - ../:/var/www/app:ro
      - ./http/server-dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 127.0.0.1:8080:80
    restart: always

  maildev:
    container_name: maildev
    image: maildev/maildev
    ports:
      - "1080:80"
    restart: always
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS

volumes:
  mysql-data:
  app-vendor:
