version: '3'

services:
  mysqldb:
    image: mariadb:10.4
    env_file:
      - environment/dev/mysql.env
    environment:
      - MYSQL_ROOT_PASSWORD=lSj58osiU12kjdj43shaSDDz
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      lpdiwa-net:
        aliases:
          - mysqldb
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    env_file:
      - environment/dev/phpmyadmin.env
    volumes:
      - /sessions
    networks:
      lpdiwa-net:
        aliases:
          - phpmyadmin
    ports:
      - 127.0.0.1:8889:80
    restart: always
  
  symfony:
    image: fguntz/symfony:2.0
    env_file:
      - environment/dev/symfony.env
    volumes:
      - ./symfony/php-dev.ini:/usr/local/etc/php/php.ini:ro
      - ./symfony/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ../:/var/www/app
      - api-vendor:/var/www/app/vendor
    working_dir: /var/www/app
    networks:
      lpdiwa-net:
        aliases:
          - symfony
    restart: always
    command: bash -c "composer install && php-fpm"

  http:
    image: nginx:1.19-alpine
    depends_on:
      - symfony
    volumes:
      - ../:/var/www/app:ro
      - ./http/server-dev.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      lpdiwa-net:
        aliases:
          - httpsrv
    ports:
      - 127.0.0.1:8080:80
    restart: always

  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"

volumes:
  mysql-data:
  api-vendor:

networks:
  lpdiwa-net:
