<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPPhZ3iS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPPhZ3iS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPPhZ3iS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPPhZ3iS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPPhZ3iS\App_KernelDevDebugContainer([
    'container.build_hash' => 'PPhZ3iS',
    'container.build_id' => '07c159b5',
    'container.build_time' => 1616068584,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPPhZ3iS');
