<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSHyAZxi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSHyAZxi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSHyAZxi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSHyAZxi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSHyAZxi\App_KernelDevDebugContainer([
    'container.build_hash' => 'SHyAZxi',
    'container.build_id' => '0df2bee9',
    'container.build_time' => 1616934541,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSHyAZxi');
