<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDN9a80Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDN9a80Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDN9a80Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDN9a80Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDN9a80Y\App_KernelDevDebugContainer([
    'container.build_hash' => 'DN9a80Y',
    'container.build_id' => 'c4398fb5',
    'container.build_time' => 1614897016,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDN9a80Y');
